# Generated by Django 3.0.4 on 2020-03-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworkplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_line_ID',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
