# Generated by Django 3.0.4 on 2020-03-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworkplace', '0002_employee_employee_line_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Respiratory_disease',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='When_respiratory_disease',
            field=models.CharField(blank=True, choices=[('1month', 'น้อยกว่า 1 เดือน'), ('1-2', 'ระหว่าง 1-2 เดือน'), ('2month', 'มากกว่า 2 เดือน')], max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='allergic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='disease',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_person1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_person1_tel',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_person2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_person2_tel',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_blood',
            field=models.CharField(blank=True, choices=[('o', 'โอ'), ('a', 'เอ'), ('b', 'บี'), ('ab', 'เอบี นอร์มอล')], max_length=6),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_gender',
            field=models.CharField(blank=True, choices=[('male', 'ชาย'), ('female', 'หญิง')], max_length=6),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_tel',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='emplyee_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emplyee_address14days',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hospital',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='late_disease',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='late_hospital',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='late_went_to_hospital',
            field=models.CharField(blank=True, choices=[('1month', 'น้อยกว่า 1 เดือน'), ('1-2', 'ระหว่าง 1-2 เดือน'), ('2month', 'มากกว่า 2 เดือน')], max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='relationship',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='who_with_you_home',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='who_with_you_home_tel',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='who_with_you_work',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='who_with_you_work_tel',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='work',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_from_home',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_tel',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='activity_text',
            field=models.TextField(default='000'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_line_ID',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emplyee_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='quarantined',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
