# Generated by Django 3.0.4 on 2020-03-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworkplace', '0003_auto_20200316_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id_up_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id_up_2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
