# Generated by Django 3.0.4 on 2020-03-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworkplace', '0004_auto_20200317_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='healthy',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='quarantined',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
