# Generated by Django 3.0.4 on 2020-03-19 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myworkplace', '0005_auto_20200317_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emplyee_name',
            new_name='employee_name',
        ),
    ]
