# Generated by Django 3.0.4 on 2020-03-19 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myworkplace', '0006_auto_20200319_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_name',
            new_name='emplyee_name',
        ),
    ]
