# Generated by Django 3.0.4 on 2020-03-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworkplace', '0008_auto_20200320_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_ID',
            field=models.CharField(max_length=255),
        ),
    ]
