# Generated by Django 3.0.4 on 2020-03-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworkplace', '0010_auto_20200323_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailemployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(max_length=255)),
                ('employeeemail', models.CharField(max_length=255)),
            ],
        ),
    ]
