# Generated by Django 3.0.4 on 2020-03-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworkplace', '0011_emailemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='LEAVE_end_date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='LEAVE_start_date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='WFH_end_date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='WFH_start_date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='healthy',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
