# Generated by Django 3.0.4 on 2020-03-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworkplace', '0012_auto_20200323_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='active_status',
            field=models.CharField(blank=True, choices=[('PEA', 'PEA'), ('WFH', 'WFH'), ('LEAVE', 'Leave'), ('COVID', 'COVID')], default='PEA', max_length=6),
        ),
        migrations.AlterField(
            model_name='employee',
            name='approved_status',
            field=models.CharField(blank=True, choices=[('Idle', 'Idle'), ('WFH', 'WFH'), ('LEAVE', 'Leave'), ('COVID', 'COVID')], default='Idle', max_length=6),
        ),
    ]
