# Generated by Django 3.0.4 on 2020-03-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworkplace', '0013_auto_20200323_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='activity_challenge',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='employee',
            name='activity_checkin',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='employee',
            name='activity_daily_update',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='activity_text',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='healthy',
            field=models.CharField(blank=True, choices=[('normal', 'ไม่เสี่ยง'), ('flu', 'ไข้หวัด'), ('quarantine', 'แยกตัว'), ('hospital', 'พบแพทย์')], max_length=255),
        ),
    ]
