# Generated by Django 3.0.4 on 2020-03-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworkplace', '0014_auto_20200323_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='activity_checkout',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_one_relationship',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_two_relationship',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='workmate_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
