# Generated by Django 3.0.4 on 2020-03-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworkplace', '0015_auto_20200325_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id_up_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id_up_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
