# Generated by Django 3.0.4 on 2020-03-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworkplace', '0019_auto_20200328_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_level_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
